version: '3.4'

services:
  server:
    image: klakegg/hugo:0.85.0-ext
    volumes:
      - .:/src/
    ports:
      - "1313:1313"
    command:
      - "server"
      - "--watch"
      - "--buildFuture"
      - "--buildDrafts"
      - "--disableFastRender"
      - "-D"
      - "--poll 700ms"
      - "--bind 0.0.0.0"
