name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: # optional
        # Whether to download only stable versions
        stable: # optional, default is true
        # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
        token: # optional, default is ${{ github.token }}

    - name: Checkout master
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/fschuch/fschuch.com

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/fschuch.com/go

    - name: Test
      run: |
        go get -u golang.org/x/tools/cmd/cover
        go get -u golang.org/x/net/context
        go get -u golang.org/x/net/context/ctxhttp
        go get -u github.com/golang/protobuf/proto
        go get -u github.com/golang/protobuf/protoc-gen-go
        go test -cover $(go list ./... | grep -v /vendor/)
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.81.0
        HUGO_EXTENDED: true
        TARGET_REPO: fschuch/fschuch.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.fschuch.com
        GOPATH: /home/runner/work/fschuch.com/go
