name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16.2' # The Go version to download (if necessary) and use.
    - run: go run hello.go

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.81.0
        HUGO_EXTENDED: true
        TARGET_REPO: fschuch/fschuch.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: www.fschuch.com
